import { Observable } from "rxjs/Observable";
import 'rxjs/add/observable/of';

export class ArticlesDataMock {
    public getArticles() {
        let articles;
        articles = {"articles":[{"id":1,"title":"US shutdown: Senate rejects bills to re-open government","description":"The US Senate has rejected two bills to end the government shutdown, leaving no end in sight to the record-breaking closure of federal agencies.","content":"The Republican legislation failed by 50-47 and the Democratic bill followed suit by 52-44. Each bill needed 60 votes to move forward. Meanwhile, 800,000 federal workers missed another payday on Friday. At 34 days with no end in sight, this is the longest shutdown in US history.","created_at":"2019-01-25T09:17:46.291Z","user":{"name":"Christiane Amanpour","email":"journalist@mail.com"},"category":{"name":"General"}},{"id":2,"title":"US shutdown: Senate rejects bills to re-open government","description":"The US Senate has rejected two bills to end the government shutdown, leaving no end in sight to the record-breaking closure of federal agencies.","content":"The Republican legislation failed by 50-47 and the Democratic bill followed suit by 52-44. Each bill needed 60 votes to move forward. Meanwhile, 800,000 federal workers missed another payday on Friday. At 34 days with no end in sight, this is the longest shutdown in US history.","created_at":"2019-01-25T09:17:46.766Z","user":{"name":"Christiane Amanpour","email":"journalist@mail.com"},"category":{"name":"General"}},{"id":3,"title":"Rafael Nadal crushes Stefanos Tsitsipas to reach Australian Open final","description":"Second seed Rafael Nadal ended Greek youngster Stefanos Tsitsipas captivating run to reach his fifth Australian Open final.","content":"Nadal, 32, was in devastating form as he beat the 20-year-old 14th seed 6-2 6-4 6-0 in one hour and 46 minutes. The Spaniard cracked 28 winners, breaking Tsitsipas serve six times and only facing one break point himself. He will play either top seed Novak Djokovic or Frances Lucas Pouille - who meet on Friday - in Sundays final.","created_at":"2019-01-25T09:17:46.895Z","user":{"name":"Christiane Amanpour","email":"journalist@mail.com"},"category":{"name":"Sports"}},{"id":4,"title":"Rafael Nadal crushes Stefanos Tsitsipas to reach Australian Open final","description":"Second seed Rafael Nadal ended Greek youngster Stefanos Tsitsipas captivating run to reach his fifth Australian Open final.","content":"Nadal, 32, was in devastating form as he beat the 20-year-old 14th seed 6-2 6-4 6-0 in one hour and 46 minutes. The Spaniard cracked 28 winners, breaking Tsitsipas serve six times and only facing one break point himself. He will play either top seed Novak Djokovic or Frances Lucas Pouille - who meet on Friday - in Sundays final.","created_at":"2019-01-25T09:17:48.306Z","user":{"name":"Christiane Amanpour","email":"journalist@mail.com"},"category":{"name":"Sports"}}]}
    
        return Observable.of(articles);
      }
}